from . import product_product
from . import product_brand_spt
from . import product_color_spt
from . import product_model_spt
from . import product_size_spt
from . import kits_product_color_code
from . import product_material_spt
from . import product_shape_spt
from . import product_rim_type_spt
from . import product_bridge_size_spt
from . import product_temple_size_spt
from . import product_aging_spt
from . import product_category
from . import res_config_settings
from . import product_template
from . import kits_package_product
from . import kits_package_product_line
from . import sale_order_line
from . import sale_order_backup_spt
from . import sale_order_backup_line_spt
from . import ir_report_action
from . import kits_package_restriction
from . import kits_package_order_line
from . import shipping_provider_spt
from . import stock_picking
from . import kits_inflation
from . import kits_inflation_rule
from . import kits_special_discount
from . import geo_restriction_spt
from . import account_move
from . import python_script_runner
from . import res_company
from . import kits_commission_lines
from . import ir_model
from . import stock_move
from . import internal_flag_spt
from . import business_type_spt
from . import mailing_contact
from . import res_country_group
from . import customer_log
from . import kits_commission_rules
from . import kits_commission_lines
from . import import_partner_spt
from . import mail_template
from . import mailgun_email_logs
from . import sale_order
from . import res_users
from . import res_partner
from . import tzc_fest_discount
from . import order_payment
from . import geo_restriction_spt
from . import business_type_spt
from . import internal_flag_spt
from . import delivery_carrier
from . import kits_shipping_error_log
from . import kits_double_move_log
from . import kits_stock_move
# from . import flash_menu_spt
from . import sale_catalog
from . import sale_catalog_line
from . import product_packaging
from . import update_qty_log
from . import mail_thread
from . import mail_tracking_value
from . import account_move_line
from . import stock_quant
from . import account_journal
# from . import kits_quickbooks_backend
from . import account_payment
from . import project_project
from . import project_task_type
from . import project_task
from . import sale_catalog_order
from . import marketing_campaign
from . import marketing_activity
from . import mailing_trace
from . import campaign_report_contacts
from . import campaign_monetization_spt
from . import stock_move_line
from . import mail_followers
from . import base_model
from . import sale_manager_tracking
from . import ir_ui_menu
from . import kits_return_ordered_items
from . import product_pricelist
from . import create_homepage_html
from . import tzc_homepage_banner
from . import fedex_request
from . import delivery_box
from . import delivery_box_line
from . import delivery_package_line
from . import account_tax
