from . import kits_warning_wizard
from . import kits_bulk_discount_on_package_products
from . import on_sale_price_wizard_spt
from . import product_info_wizard_spt
from . import kits_assign_salesperson_wizard
from . import kits_change_contact_country
from . import warning_spt_wizard
from . import sales_commission_report_wizard
from . import portal_users_message_wizard_spt
from . import portal_wizard
from . import portal_wizard_user
from . import pricelist_partner_wizard_spt
from . import eto_partner_wizard_spt
from . import followup_send_wizard
from . import warning_message_wizard
from . import kits_confirm_contact_delete_wizard
from . import customer_from_invitation_wizard_spt
from . import kits_customers_report_wizard
from . import kits_replace_sales_person_wizard
from . import kits_replace_sales_manager_wizard
from . import kits_change_commission_rule
from . import paid_amount_wizard
