from . import kits_warning_wizard
from . import kits_bulk_discount_on_package_products
from . import on_sale_price_wizard_spt
from . import sale_barcode_order_spt
from . import on_consignment_product_message_wizard
from . import geo_restriction_message_wizard_spt
from . import discount_on_sale_order_line_wizard_spt
from . import remove_product_spt
from . import update_partner_in_order_wizard_spt
from . import add_shipping_cost_wizard
from . import add_admin_fee_wizard
from . import add_aditional_discount_wizard
from . import kits_create_credit_note_wizard
# from . import kits_wizard_return_picking
from . import kits_message_wizard
from . import kits_generate_payment_link_wizard
from . import sale_order_report_wizard_spt
from . import import_order_lines_wizard_spt
from . import order_report_with_image_wizard
from . import sales_report_for_sales_person_wizard_spt
from . import shipped_orders_report_wizard_spt
from . import kits_brand_sales_report_wizard
from . import kits_search_sale_order_wizard
from . import product_info_wizard_spt
from . import kits_assign_salesperson_wizard
from . import kits_change_contact_country
from . import product_import_by_sku_wizard
from . import shipping_cost_analysis_wizard
from . import reserved_product_report
from . import warning_spt_wizard
from . import sales_commission_report_wizard
from . import portal_users_message_wizard_spt
from . import portal_wizard
from . import portal_wizard_user
from . import pricelist_partner_wizard_spt
from . import eto_partner_wizard_spt
from . import followup_send_wizard
from . import warning_message_wizard
from . import kits_confirm_contact_delete_wizard
from . import customer_from_invitation_wizard_spt
from . import kits_customers_report_wizard
from . import kits_replace_sales_person_wizard
from . import kits_replace_sales_manager_wizard
from . import kits_change_commission_rule
from . import paid_amount_wizard
from . import discount_on_catalog_line_wizard_spt
from . import kits_wizard_download_catalog_excel
from . import create_catalog_quotation_wizard_spt
from . import product_report_on_date_wizard_spt
from . import bank_inventory_report_wizard
from . import brand_qty_report
# from . import choose_delivery_carrier
# from . import choose_delivery_package
from . import kits_scan_package_products
from . import kits_remove_package_products
from . import stock_picking_barcode_spt
from . import barcode_error_message_wizard_spt
from . import remove_done_quantity_spt
from . import kits_update_picking_wizard
from . import sale_make_invoice_advance
from . import delivery_recovery_selection_wizard
from . import kits_task_report_of_users
from . import kits_history_of_task_changes
from . import time_shift_wizard
from . import product_edit_wizard_spt
# from . import product_edit_wizard_line_spt
from . import mail_compose_message_wizard
from . import mass_mailing_message_wizard
from . import stock_change_product_qty
from . import kits_message_update_picking_wizard
