# -*- coding: utf-8 -*-
{
    'name': 'ETO Sales Customization',
    'summary': 'ETO Sales Customization',
    'description': """
    """,
    'author': 'Keypress',
    'sequence': 1,
    'version': '16.0.0',
    'depends':['base','product','stock','sale_stock','sale','sale_management','crm','delivery','mail','portal','mass_mailing','snailmail_account_followup','marketing_automation','barcodes','sale_loyalty','project_enterprise','project'],

    'data': [
        
        # Access rules
        'security/res_groups.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'security/cancel_sale_order_rule_spt.xml',

        # Data
        'data/ir_server_actions.xml',
        'data/mail_template_backend_quotation.xml',
        'data/mail_template_of_order_completion.xml',
        'data/mail_template_cart_recovery.xml',
        'data/mail_template_salesperson_abandone_cart.xml',
        'data/mail_template_ready_to_ship_order.xml',
        'data/mail_templates_stock_picking.xml',
        'data/mail_template_warehouse_abandone_cart.xml',
        'data/mail_send_download_image_email.xml',
        'data/mail_template_sale_cart_recovery.xml',
        'data/report_paperformat.xml',
        'data/mail_template_sales_person_order_confirm.xml',
        'data/mail_template_purchase_start.xml',
        'data/cron_spt.xml',
        'data/data.xml',
        'data/mail_template_customer_approve.xml',
        'data/mail_template_notify_admin_partner_country_change.xml',
        'data/pricelist.xml',
        'data/seq.xml',
        'data/mail_change_commission_rule_for_salesperson.xml',
        # 'data/error_message_mail_template.xml',
        'data/base_mail_template_spt.xml',
        'data/mail_template_bulk_mail_sent.xml',
        'data/activate_account_data.xml',
        'data/signup_confirmation_data.xml',
        'data/mail_template_customer_approve_notify.xml',
        'data/mail_template_new_user_spt.xml',
        'data/stock_picking_mail_templates.xml',
        'data/mail_template_catalog_pending.xml',
        'data/payment_mail_template.xml',
        'data/send_payment_link_mail_template.xml',
        'data/mail_template_warehouse_abandone_cart.xml',

        # Views
        'views/product_product_view.xml',
        'views/product_template_view.xml',
        'views/product_brand_view_spt.xml',
        'views/product_color_spt_view.xml',
        'views/product_model_view_spt.xml',
        'views/product_size_view_spt.xml',
        'views/product_material_spt.xml',
        'views/product_shape_view_spt.xml',
        'views/product_rim_type_view_spt.xml',
        'views/product_bridge_size_spt.xml',
        'views/product_temple_size_spt.xml',
        'views/product_aging_view_spt.xml',
        'views/product_category_view.xml',
        'views/res_config_settings_view.xml',
        # 'views/order_payment_view.xml',
        'views/kits_package_restriction_view.xml',
        'views/kits_package_product_view.xml',
        'views/sale_order_backup_view_spt.xml',
        'views/sale_order.xml',
        'views/kits_special_discount_view.xml',
        'views/tzc_fest_discount_view.xml',
        'views/geo_restriction_spt.xml',
        'views/python_script_runner_view.xml',
        'views/res_company.xml',
        'views/stock_picking_view.xml',
        'views/shipping_provider_spt_view.xml',
        'views/res_partner_view.xml',
        'views/kits_commission_rules_view.xml',
        'views/import_partner_spt_view.xml',
        'views/manage_template_view.xml',
        'views/mailgun_email_logs_view.xml',
        'views/kits_commission_lines_view.xml',
        'views/order_payments_view.xml',
        'views/kits_inflation.xml',
        'views/business_type_view_spt.xml',
        'views/internal_flag_view_spt.xml',
        'views/kits_shipping_error_log_view.xml',
        'views/kits_double_move_log.xml',
        'views/flash_menu_spt.xml',
        # 'views/kits_inflation_rule.xml',
        'views/account_move_view.xml',
        'views/res_users_view.xml',
        'views/login_user_views.xml',
        # 'views/update_qty_log_view.xml',
        'views/sale_catalog.xml',
        'views/project_task_view.xml',
        'views/project_task_type_view.xml',

        # Wizard
        'wizards/kits_warning_wizard_view.xml',
        'wizards/kits_bulk_discount_on_package_products_view.xml',
        'wizards/on_sale_price_wizard_spt.xml',
        'wizards/sale_barcode_order_view_spt.xml',
        'wizards/geo_restriction_message_wizard.xml',
        'wizards/discount_on_sale_order_line_wizard_spt.xml',
        'wizards/update_partner_in_order_wizard_spt.xml',
        'wizards/add_aditional_discount_wizard.xml',
        'wizards/add_admin_fee_wizard.xml',
        'wizards/add_shipping_cost_wizard.xml',
        'wizards/kits_create_credit_note_wizard_view.xml',
        'wizards/kits_wizard_return_picking_view.xml',
        'wizards/kits_message_wizard_view.xml',
        'wizards/kits_generate_payment_link_wizard_view.xml',
        'wizards/sale_order_report_wizard_spt.xml',
        'wizards/import_order_lines_wizard_view_spt.xml',
        'wizards/remove_product_wizard_spt_view.xml',
        'wizards/order_report_with_image_wizard_view.xml',
        'wizards/sales_report_for_sales_person_wizard_spt.xml',
        'wizards/shipped_orders_report_wizard_view.xml',
        'wizards/kits_brand_sales_report_wizard.xml',
        'wizards/kits_search_sale_order_view.xml',
        'wizards/product_info_wizard_spt.xml',
        'wizards/product_import_by_sku_wizard_view.xml',
        'wizards/shipping_cost_analysis_wizard.xml',
        'wizards/reserved_product_report_view.xml',
        'wizards/kits_assign_salesperson_wizard_view.xml',
        'wizards/kits_change_contact_country_view.xml',
        'wizards/warning_spt_wizard_view.xml',
        'wizards/product_report_on_date_wizard_spt.xml',
        'wizards/bank_inventory_report_wizard_view.xml',
        'wizards/brand_qty_report_view.xml',
        # 'wizards/choose_delivery_carrier_views.xml',
        # 'wizards/choose_delivery_package_views.xml',
        'wizards/sales_commission_report_wizard_view.xml',
        'wizards/portal_users_message_wizard_spt_view.xml',
        'wizards/portal_wizard_view.xml',
        'wizards/pricelist_partner_wizard_spt_view.xml',
        'wizards/eto_partner_wizard_spt_view.xml',
        'wizards/followup_send_wizard_view.xml',
        'wizards/warning_message_wizard_view.xml',
        'wizards/kits_confirm_contact_delete_wizard_view.xml',
        'wizards/customer_from_invitation_wizard_spt_view.xml',
        'wizards/kits_customers_report_wizard_view.xml',
        'wizards/kits_replace_sales_person_wizard_view.xml',
        'wizards/kits_replace_sales_manager_wizard_view.xml',
        'wizards/kits_change_commission_rule_view.xml',
        'wizards/paid_amount_wizard_view.xml',
	 'wizards/discount_on_catalog_line_wizard_spt.xml',
        'wizards/kits_wizard_download_catalog_excel_view.xml',
        'wizards/create_catalog_quotation_wizard_spt.xml',
        'wizards/catalog_process_error_wizard_view_spt.xml',
        'wizards/kits_scan_package_products_view.xml',
        'wizards/barcode_error_message_wizard_spt.xml',
        'wizards/stock_picking_barcode_spt.xml',
        'wizards/account_invoice_send_views.xml',
        'wizards/kits_update_picking_wizard_view.xml',
        'wizards/delivery_recovery_selection_wizard_view.xml',
        'wizards/remove_done_quantity_view_spt.xml',
        'wizards/kits_task_report_of_users_view.xml',
        'wizards/kits_history_of_task_changes_view.xml',
        'wizards/time_shift_wizard_view.xml',

        # Reports
        'reports/kits_commission_report.xml',
        'reports/sales_commission_pdf_report.xml',
        'reports/catalog_report_template_spt.xml',
        'reports/sale_catalog_report_spt.xml',
        'reports/report_template_sales_preson_spt.xml',
        'reports/shipped_orders_report_spt.xml',
        'reports/shipped_orders_report_template_spt.xml',
        'reports/catalog_report_template_spt.xml',
        'reports/report_saleorder_spt.xml',
        'reports/shipping_details_b13a_report.xml',
        'reports/report_action.xml',
        'reports/report_invoice_documnet.xml',
        'reports/report_footer_spt.xml',
        'reports/product_product_templates.xml',
        'reports/product_label_pdf_report.xml',

        # Templates
        'template/excel_data.xml',

    ],
    
    'qweb': [
        'static/src/xml/kits_task_gantt.xml',
    ],

    'assets': 
    {
        'web.assets_backend': [
            'tzc_sales_customization_spt/static/src/**/*.js',
            'tzc_sales_customization_spt/static/src/**/*.scss',
        ],
        'web.assets_common': [
            'tzc_sales_customization_spt/static/src/scss/web.zoomodoo.scss',
        ],
    },

    'application': True,
    'installable': True,
    'auto_install': False,
}
