from . import kits_b2b_website
from . import kits_b2b_website_slider
from . import kits_b2b_menus
from . import kits_b2b_pages
from . import kits_b2b_home_advertisement
from . import kits_b2b_image_model
from . import kits_b2b_key_value_model
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import kits_b2b_multi_currency_mapping
from . import res_users
from . import kits_b2b_user_token
from . import kits_b2b_product_wishlist
from . import kits_b2b_recent_view
from . import product_product
from . import sale_catalog
from . import crm_lead
from . import kits_landing_view
from . import kits_special_discount_offers